#!/usr/bin/env python3
"""Render per-version, per-store listing copy from the single source.

    python3 tools/render-version-listing.py            # writes
    python3 tools/render-version-listing.py --check     # verifies, writes nothing

⚠️ THIS GENERATES; IT DOES NOT DUPLICATE. `store-assets/listing/<locale>.md`
stays the only place the copy is written. Those files open by saying "copy kept
twice is copy that disagrees with itself eventually", and a hand-made second
copy under a version folder is precisely that: the day someone fixes a typo in
one, the store gets the other.

So the version folder is derived, and `store-listing.test.ts` runs `--check` so
a source edit that is not re-rendered fails the build instead of shipping.

⚠️ THE TWO STORES DO NOT TAKE THE SAME FIELDS, which is the whole reason for
splitting them. App Store Connect has Subtitle, Keywords and Promotional text
and no Short description; Play has Short description and neither of the other
three. Handing someone a single file to paste from means reading past the
fields that do not apply, every time.
"""
import io
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, 'store-assets', 'listing')
LOCALES = ('en-US', 'pt-BR', 'es-419')

# (block in the source, field name in that console, limit)
APP_STORE = [
    ('App name', 'Name', 30),
    ('Subtitle', 'Subtitle', 30),
    ('Keywords', 'Keywords', 100),
    ('Promotional text', 'Promotional Text', 170),
    ('Full description', 'Description', 4000),
    ('Release notes', "What's New in This Version", 4000),
]
PLAY = [
    ('App name', 'App name', 30),
    ('Short description', 'Short description', 80),
    ('Full description', 'Full description', 4000),
    ('Release notes', "What's new", 500),
]

# ⚠️ The console's own name for the language, which is NOT the repo's code.
# App Store Connect offered only Spain and Mexico for Spanish, and Spain is the
# one chosen — the copy is regionally neutral, so it reads correctly there.
CONSOLE_LOCALE = {
    'app-store': {'en-US': 'English (U.S.)', 'pt-BR': 'Portuguese (Brazil)', 'es-419': 'Spanish (Spain)'},
    'play': {'en-US': 'English (United States) – en-US', 'pt-BR': 'Portuguese (Brazil) – pt-BR', 'es-419': 'Spanish (Latin America) – es-419'},
}
STORE_TITLE = {'app-store': 'App Store Connect', 'play': 'Google Play Console'}


def block(text, name):
    """The fenced payload under `## <name>`, which is the paste-ready part."""
    m = re.search(r'^## %s\s*$(.*?)^```text\s*$(.*?)^```' % re.escape(name), text, re.M | re.S)
    if not m:
        raise SystemExit('::error::%s has no "%s" block' % (name, name))
    return m.group(2).strip('\n')


def render(store, locale, version, source):
    fields = APP_STORE if store == 'app-store' else PLAY
    out = [
        '# %s — %s — %s' % (STORE_TITLE[store], CONSOLE_LOCALE[store][locale], version),
        '',
        '<!-- GENERATED by tools/render-version-listing.py — edit',
        '     store-assets/listing/%s.md instead, then re-run it. -->' % locale,
        '',
        'Every fenced block is exactly what goes in the field above it, and',
        'nothing else in this file is.',
        '',
    ]
    for name, field, limit in fields:
        body = block(source, name)
        out += ['## %s' % field, '', '`%d / %d`' % (len(body), limit), '', '```text', body, '```', '']
    return '\n'.join(out).rstrip('\n') + '\n'


def main():
    check = '--check' in sys.argv
    version = json.load(io.open(os.path.join(ROOT, 'package.json'), encoding='utf-8'))['version']
    stale = []
    for store in ('app-store', 'play'):
        for locale in LOCALES:
            source = io.open(os.path.join(SOURCE, '%s.md' % locale), encoding='utf-8').read()
            body = render(store, locale, version, source)
            target = os.path.join(ROOT, 'store-assets', version, 'listing', store, '%s.md' % locale)
            rel = os.path.relpath(target, ROOT).replace(os.sep, '/')
            if check:
                current = io.open(target, encoding='utf-8').read() if os.path.exists(target) else None
                if current != body:
                    stale.append(rel)
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            io.open(target, 'w', encoding='utf-8', newline='\n').write(body)
            print('  wrote %s' % rel)
    if check:
        if stale:
            raise SystemExit(
                '::error::out of date with store-assets/listing/: %s\n'
                '  run: python3 tools/render-version-listing.py' % ', '.join(stale))
        print('  every generated listing matches its source')


if __name__ == '__main__':
    main()
