import React, { useMemo, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useLocale } from '@/application/providers/LocaleProvider';
import { Icon } from '@/components/Icon';
import { TabBar, type TabName } from '@/components/TabBar';
import { TipsScreen } from '@/screens/TipsScreen';
import { encode, type MorseSymbol } from '@/core/domain/morse';
import { theme } from '@/theme';

/**
 * The reference order, from the artboard: letters, then the three accents with
 * codes of their own, then the digits. Not `SUPPORTED_CHARACTERS`, which also
 * carries punctuation and is ordered by the encoding table rather than for
 * reading.
 */
const REFERENCE = 'ABCDEFGHIJKLMNOPQRSTUVWXYZÇÉÑ1234567890';

/** The example the silence section turns on. */
const AMBIGUOUS = '···---···';

type Props = Readonly<{
  onSelectTab: (tab: TabName) => void;
  unavailableTabs: readonly TabName[];
}>;

/**
 * What Morse is, the alphabet, and why the gaps matter — built from
 * `design/screens/Learn.dc.html`.
 *
 * The grid is generated by encoding each character rather than transcribed,
 * so the reference cannot drift from what the app actually sends.
 */
export function LearnScreen({ onSelectTab, unavailableTabs }: Props): React.JSX.Element {
  const { t } = useLocale();
  const insets = useSafeAreaInsets();
  const [tips, setTips] = useState(false);

  const alphabet = useMemo(
    (): readonly Readonly<{ char: string; marks: readonly MorseSymbol[] }>[] =>
      Array.from(REFERENCE).map((char) => ({
        char,
        marks: encode(char).words[0]?.letters[0]?.symbols ?? [],
      })),
    [],
  );

  if (tips) {
    return (
      <TipsScreen
        onBack={() => {
          setTips(false);
        }}
      />
    );
  }

  return (
    <View style={[styles.screen, { paddingTop: insets.top }]} testID="learn-screen">
      <View style={styles.header}>
        <Text style={styles.wordmark}>{t('learn.title')}</Text>
      </View>

      <ScrollView style={styles.scroll} contentContainerStyle={styles.content}>
        <View style={styles.card}>
          <Text style={styles.sectionTitle}>{t('learn.whatTitle')}</Text>
          <Text style={styles.body}>{t('learn.whatBody')}</Text>
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>{t('learn.alphabet')}</Text>
          <View style={styles.card}>
            <View style={styles.grid} testID="learn-alphabet">
              {alphabet.map((entry) => (
                <View key={entry.char} style={styles.cell} testID="learn-letter">
                  <View style={styles.marks}>
                    {entry.marks.map((mark, index) => (
                      <View
                        key={`m${String(index)}`}
                        style={mark === '.' ? styles.dot : styles.dash}
                      />
                    ))}
                  </View>
                  <Text style={styles.char}>{entry.char}</Text>
                </View>
              ))}
            </View>
            <Text style={styles.note}>{t('learn.accents')}</Text>
          </View>
        </View>

        <View style={styles.block}>
          <Text style={styles.label}>{t('learn.silence')}</Text>
          <View style={styles.card}>
            <Text style={styles.body}>
              {t('learn.silenceBody')} <Text style={styles.example}>{AMBIGUOUS}</Text>{' '}
              {t('learn.silenceAfter')}
            </Text>
          </View>
        </View>

        <Pressable
          testID="learn-tips"
          accessibilityRole="button"
          accessibilityLabel="learn-tips"
          onPress={() => {
            setTips(true);
          }}
          style={({ pressed }) => [styles.tipsCard, pressed && styles.pressed]}
        >
          <View style={styles.tipsCopy}>
            <Text style={styles.tipsTitle}>{t('learn.tipsTitle')}</Text>
            <Text style={styles.tipsSubtitle}>{t('learn.tipsSubtitle')}</Text>
          </View>
          <Icon
            name="chevronDown"
            size={20}
            color={theme.color.accentDeep}
            strokeWidth={2.2}
          />
        </Pressable>
      </ScrollView>

      <TabBar active="learn" onSelect={onSelectTab} unavailable={unavailableTabs} />
    </View>
  );
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.color.ground },
  header: { height: 48, justifyContent: 'center', paddingHorizontal: theme.gutter },
  wordmark: { ...theme.type.wordmark, color: theme.color.ink },
  scroll: { flex: 1 },
  content: {
    paddingHorizontal: theme.gutter,
    paddingTop: 10,
    paddingBottom: theme.spacing.xl,
    gap: theme.spacing.lg,
  },
  block: { gap: theme.spacing.sm },
  label: { ...theme.type.label, color: theme.color.faint, paddingHorizontal: 4 },
  card: {
    padding: 16,
    backgroundColor: theme.color.surface,
    borderRadius: theme.radius.card,
    boxShadow: theme.shadow.card,
    gap: theme.spacing.md,
  },
  sectionTitle: { ...theme.type.action, fontSize: 16, color: theme.color.ink },
  body: { ...theme.type.body, fontSize: 15, lineHeight: 22, color: theme.color.muted },
  example: { ...theme.type.monoLarge, fontSize: 15, color: theme.color.accent },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.sm },
  // Four to a row, as the artboard's grid does, without a grid engine. The
  // basis is under a quarter so four fit once the gaps are taken out, and
  // flexGrow shares the remainder back — which also keeps the last, short row
  // aligned with the ones above it.
  cell: {
    flexBasis: '22%',
    flexGrow: 1,
    maxWidth: '25%',
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    paddingVertical: theme.spacing.sm,
    backgroundColor: theme.color.ground,
    borderRadius: theme.radius.control,
  },
  marks: { flexDirection: 'row', alignItems: 'center', gap: 2, height: 6 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: theme.color.accent },
  dash: { width: 11, height: 6, borderRadius: 3, backgroundColor: theme.color.accent },
  char: { ...theme.type.letter, color: theme.color.muted },
  note: { ...theme.type.hint, lineHeight: 18, color: theme.color.muted },
  tipsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: theme.spacing.md,
    minHeight: 68,
    padding: 18,
    backgroundColor: theme.color.accentTint,
    borderRadius: theme.radius.card,
  },
  pressed: { opacity: 0.85 },
  tipsCopy: { flex: 1, gap: 2 },
  tipsTitle: { ...theme.type.action, fontSize: 16, color: theme.color.accentDeep },
  tipsSubtitle: { ...theme.type.body, fontSize: 13, color: '#3f8d84' },
});
